# Site
repository:
favicon: images/favicon.ico

# Personal info
name: David Oh
title: Corporate System Engineer
email: davidoh923@gmail.com
website: www.github.com/davidoh923

# Social links
github_username:  davidoh923
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: d0hgram
linkedin_username: davidoh2
# pinterest_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is David and I'm a Corporate System Engineer. To work diligently, improve knowledge and gain general experience in the industry. I am seeking a position where I can develop and excel while giving my best to an employer.

  I am most skilled in: <mark>AWS</mark> and <mark>Sleeping</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in systems and software engineering some of my other interests and hobbies are:
   - Snowboarding
   - Camping
   - Gaming

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-cayman
